/* Generated by AN DISI Unibo */ 
package it.unibo.planexecutor

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Planexecutor ( name: String, scope: CoroutineScope ) : ActorBasicFsm( name, scope){
 	
	override fun getInitialState() : String{
		return "s0"
	}
		
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		
			  var mapEmpty = true
			  val mapname = "roommap"
			  //var Tback = 100 
		
			  var Curmove = ""
			  var curmoveIsForward = false
		
			  var CurGoal = ""
		
			  //REAL ROBOT
			  //var StepTime = 1000
			  //var PauseTime = 500L
		
			  //VIRTUAL ROBOT
			  var StepTime = 330
			  var PauseTime = 400	//increased because it wouldn't do two rotations in a row
		
			  var PauseTimeL = PauseTime.toLong()
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						solve("consult('moves.pl')","") //set resVar	
						itunibo.planner.plannerUtil.initAI(  )
						itunibo.planner.moveUtils.loadRoomMap(myself ,mapname )
						itunibo.planner.moveUtils.showCurrentRobotState(  )
						val MapStr = itunibo.planner.plannerUtil.getMapOneLine()
						forward("modelUpdate", "modelUpdate(roomMap,$MapStr)" ,"resourcemodel" ) 
					}
					 transition( edgeName="goto",targetState="waitCmd", cond=doswitch() )
				}	 
				state("waitCmd") { //this:State
					action { //it:State
					}
					 transition(edgeName="t012",targetState="createPlan",cond=whenDispatch("goalUpdate"))
				}	 
				state("createPlan") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						if( checkMsgContent( Term.createTerm("goalUpdate(G,X,Y)"), Term.createTerm("goalUpdate(G,X,Y)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								CurGoal = payloadArg(0)
								itunibo.planner.plannerUtil.setGoal( payloadArg(1), payloadArg(2)  )
						}
						itunibo.planner.moveUtils.doPlan(myself)
					}
					 transition( edgeName="goto",targetState="executePlannedActions", cond=doswitch() )
				}	 
				state("executePlannedActions") { //this:State
					action { //it:State
						solve("retract(move(M))","") //set resVar	
						if(currentSolution.isSuccess()) { 
									  Curmove = getCurSol("M").toString()
									  curmoveIsForward = (Curmove == "w")
						 }
						else
						{ 
									  Curmove = ""
									  curmoveIsForward = false
						 }
						println("executePlannedActions doing $Curmove")
					}
					 transition( edgeName="goto",targetState="cheakAndDoAction", cond=doswitchGuarded({(Curmove.length > 0)}) )
					transition( edgeName="goto",targetState="goalOk", cond=doswitchGuarded({! (Curmove.length > 0)}) )
				}	 
				state("goalOk") { //this:State
					action { //it:State
						forward("goalOk", "goalOk($CurGoal)" ,"roombutlerrobot" ) 
					}
					 transition( edgeName="goto",targetState="waitCmd", cond=doswitch() )
				}	 
				state("cheakAndDoAction") { //this:State
					action { //it:State
					}
					 transition( edgeName="goto",targetState="doForwardMove", cond=doswitchGuarded({curmoveIsForward}) )
					transition( edgeName="goto",targetState="doTheMove", cond=doswitchGuarded({! curmoveIsForward}) )
				}	 
				state("doTheMove") { //this:State
					action { //it:State
						itunibo.planner.moveUtils.rotate(myself ,Curmove, PauseTime )
					}
					 transition( edgeName="goto",targetState="executePlannedActions", cond=doswitch() )
				}	 
				state("doForwardMove") { //this:State
					action { //it:State
						delay(PauseTimeL)
						itunibo.planner.moveUtils.attemptTomoveAhead(myself ,StepTime )
					}
					 transition(edgeName="t013",targetState="handleStepOk",cond=whenDispatch("stepOk"))
					transition(edgeName="t014",targetState="handleStepFail",cond=whenDispatch("stepFail"))
				}	 
				state("handleStepOk") { //this:State
					action { //it:State
						itunibo.planner.moveUtils.updateMapAfterAheadOk(myself)
						val MapStr = itunibo.planner.plannerUtil.getMapOneLine()
						forward("modelUpdate", "modelUpdate(roomMap,$MapStr)" ,"resourcemodel" ) 
						itunibo.planner.moveUtils.showCurrentRobotState(  )
					}
					 transition( edgeName="goto",targetState="executePlannedActions", cond=doswitch() )
				}	 
				state("handleStepFail") { //this:State
					action { //it:State
						println("NEVER HERE!")
					}
				}	 
			}
		}
}
