/* Generated by AN DISI Unibo */ 
package it.unibo.ctxDummyForRBR
import it.unibo.kactor.QakContext
import it.unibo.kactor.sysUtil
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
	QakContext.createContexts(
	        "robothost", this, "fridge.pl", "sysRules.pl"
	)
}

