/* Generated by AN DISI Unibo */ 
package it.unibo.ctxDummyForFridge
import it.unibo.kactor.QakContext
import it.unibo.kactor.sysUtil
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
	QakContext.createContexts(
	        "fridgehost", this, "roombutlerrobot.pl", "sysRules.pl"
	)
}

